
for delfile in instances/v000022.txt instances/v000033.txt instances/v000025.txt instances/v000034.txt instances/v000038.txt instances/v000040.txt instances/v000036.txt instances/v000035.txt instances/v000031.txt instances/v000037.txt instances/v000032.txt instances/v000029.txt instances/v000029.txt instances/v000029.txt instances/v000024.txt instances/v000037.txt instances/v000032.txt instances/v000024.txt instances/v000037.txt instances/v000032.txt instances/v000024.txt instances/v000023.txt instances/v000026.txt instances/v000030.txt instances/v000027.txt instances/v000039.txt instances/v000041.txt instances/v000042.txt  instances/v000028.txt
do
  rm -f $delfile
done 

while read filevar filein
do

echo "--- adverbs $filevar ---"

 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000022.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -v 'form=".*_.*"' | grep 'form=".........."' | pcregrep -v 'form="é"|form="É"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000033.txt 		#at least 10 letters, not compound
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep 'form=".*_.*"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000025.txt 				
 
 # advother adv.adverb_except_time_manner_place.advother
 
 
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="form="bastante"|form="demais"|form="mais"|form="menos"|form="bem"|form="muito"|form="quanto"|form="quão"|form="quase"|form="tanto"|form="pouco"|form="demasiado"|form="imenso"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="tecnicamente"|base="tipicamente"|base="francamente"|base="declaradamente"|base="previamente"|base="sinceramente"|base="primeiramente"|base="imediatamente"|base="estritamente"|base="altamente"|base="juntamente"|base="honestamente"|base="relativamente"|base="figurativamente"|base="respectivamente"|base="novamente"|base="recentemente"|base="especialmente"|base="inicialmente"|base="confidencialmente"|base="essencialmente"|base="normalmente"|base="principalmente"|base="geralmente"|base="igualmente"|base="atualmente"|base="anteriormente"|base="posteriormente"|base="segundo"|base="de".*\n.*base="esse".*\n.*base="modo"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="aparentemente"|base="aproximadamente"|base="diariamente"|base="evidentemente"|base="frequentemente"|base="freqüentemente"|base="grosseiramente"|base="maior".*\n.*base="parte".*\n.*base="dos".*\n.*base="casos"|base="parcialmente"|base="possivelmente"|base="previsivelmente"|base="provavelmente"|base="quase".*\n.*base="sempre"|base="quem".*\n.*base="sabe"|base="talvez"|base="tipo".*\n.*base="de"|base="uma".*\n.*base="espécie".*\n.*base="de"|form="acaso"|form="casualmente"|form="porventura"|form="possivelmente"|form="talvez"|form="quiçá"|form="será"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="absolutamente"|base="amplamente"|base="certamente"|base="claramente"|base="claro"|base="com".*\n.*base="certeza"|base="completamente"|base="consequentemente"|base="conseqüentemente"|base="de".*\n.*base="fato"|base="definitivamente"|base="diretamente"|base="efetivamente"|base="exatamente"|base="exclusivamente"|base="extremamente"|base="facilmente"|base="finalmente"|base="fortemente"|base="independentemente"|base="inevitavelmente"|base="inteiramente"|base="jamais"|base="na".*\n.*base="realidade"|base="naturalmente"|base="necessariamente"|base="nunca"|base="obviamente"|base="particularmente"|base="propriamente"|base="realmente"|base="sem".*\n.*base="dúvida"|base="sempre"|base="significativamente"|base="simplesmente"|base="somente"|base="decerto"|base="certo"|base="sim"|base="não"|base="totalmente"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="absoluta"|base="de".*\n.*base="maneira".*\n.*base="ampla"|base="de".*\n.*base="maneira".*\n.*base="certa"|base="de".*\n.*base="maneira".*\n.*base="clara"|base="de".*\n.*base="maneira".*\n.*base="completa"|base="de".*\n.*base="maneira".*\n.*base="consequente"|base="de".*\n.*base="maneira".*\n.*base="conseqüente"|base="de".*\n.*base="maneira".*\n.*base="definitiva"|base="de".*\n.*base="maneira".*\n.*base="direta"|base="de".*\n.*base="maneira".*\n.*base="efetiva"|base="de".*\n.*base="maneira".*\n.*base="exata"|base="de".*\n.*base="maneira".*\n.*base="exclusiva"|base="de".*\n.*base="maneira".*\n.*base="extrema"|base="de".*\n.*base="maneira".*\n.*base="fácil"|base="de".*\n.*base="maneira".*\n.*base="final"|base="de".*\n.*base="maneira".*\n.*base="forte"|base="de".*\n.*base="maneira".*\n.*base="independente"|base="de".*\n.*base="maneira".*\n.*base="inevitável"|base="de".*\n.*base="maneira".*\n.*base="inteira"|base="de".*\n.*base="maneira".*\n.*base="natural"|base="de".*\n.*base="maneira".*\n.*base="necessária"|base="de".*\n.*base="maneira".*\n.*base="óbvia"|base="de".*\n.*base="maneira".*\n.*base="particular"|base="de".*\n.*base="maneira".*\n.*base="própria"|base="de".*\n.*base="maneira".*\n.*base="real"|base="de".*\n.*base="maneira".*\n.*base="significativa"|base="de".*\n.*base="maneira".*\n.*base="simples"|base="de".*\n.*base="maneira".*\n.*base="sa"|base="de".*\n.*base="maneira".*\n.*base="total"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="absoluto"|base="de".*\n.*base="modo".*\n.*base="amplo"|base="de".*\n.*base="modo".*\n.*base="certo"|base="de".*\n.*base="modo".*\n.*base="claro"|base="de".*\n.*base="modo".*\n.*base="completo"|base="de".*\n.*base="modo".*\n.*base="consequente"|base="de".*\n.*base="modo".*\n.*base="conseqüente"|base="de".*\n.*base="modo".*\n.*base="definitivo"|base="de".*\n.*base="modo".*\n.*base="direto"|base="de".*\n.*base="modo".*\n.*base="efetivo"|base="de".*\n.*base="modo".*\n.*base="exato"|base="de".*\n.*base="modo".*\n.*base="exclusivo"|base="de".*\n.*base="modo".*\n.*base="extremo"|base="de".*\n.*base="modo".*\n.*base="fácil"|base="de".*\n.*base="modo".*\n.*base="final"|base="de".*\n.*base="modo".*\n.*base="forte"|base="de".*\n.*base="modo".*\n.*base="independente"|base="de".*\n.*base="modo".*\n.*base="inevitável"|base="de".*\n.*base="modo".*\n.*base="inteiro"|base="de".*\n.*base="modo".*\n.*base="natural"|base="de".*\n.*base="modo".*\n.*base="necessário"|base="de".*\n.*base="modo".*\n.*base="óbvio"|base="de".*\n.*base="modo".*\n.*base="particular"|base="de".*\n.*base="modo".*\n.*base="próprio"|base="de".*\n.*base="modo".*\n.*base="real"|base="de".*\n.*base="modo".*\n.*base="significativo"|base="de".*\n.*base="modo".*\n.*base="simples"|base="de".*\n.*base="modo".*\n.*base="so"|base="de".*\n.*base="modo".*\n.*base="total"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="acertadamente"|base="convenientemente"|base="curiosamente"|base="espantosamente"|base="esperançosamente"|base="felizmente"|base="impressionantemente"|base="inacreditavelmente"|base="infelizmente"|base="ironicamente"|base="lamentavelmente"|base="mesmo"|base="sabiamente"|base="sensatamente"|base="sequer"|base="surpreendentemente"|base="tristemente"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="técnico"|base="de".*\n.*base="modo".*\n.*base="típico"|base="de".*\n.*base="modo".*\n.*base="franco"|base="de".*\n.*base="modo".*\n.*base="declarado"|base="de".*\n.*base="modo".*\n.*base="prévio"|base="de".*\n.*base="modo".*\n.*base="sincero"|base="de".*\n.*base="modo".*\n.*base="primeiro"|base="de".*\n.*base="modo".*\n.*base="imediato"|base="de".*\n.*base="modo".*\n.*base="estrito"|base="de".*\n.*base="modo".*\n.*base="alto"|base="de".*\n.*base="modo".*\n.*base="junto"|base="de".*\n.*base="modo".*\n.*base="honesto"|base="de".*\n.*base="modo".*\n.*base="relativo"|base="de".*\n.*base="modo".*\n.*base="figurativo"|base="de".*\n.*base="modo".*\n.*base="respectivo"|base="de".*\n.*base="modo".*\n.*base="novo"|base="de".*\n.*base="modo".*\n.*base="recente"|base="de".*\n.*base="modo".*\n.*base="especial"|base="de".*\n.*base="modo".*\n.*base="inicial"|base="de".*\n.*base="modo".*\n.*base="confidencial"|base="de".*\n.*base="modo".*\n.*base="essencial"|base="de".*\n.*base="modo".*\n.*base="normal"|base="de".*\n.*base="modo".*\n.*base="principal"|base="de".*\n.*base="modo".*\n.*base="geral"|base="de".*\n.*base="modo".*\n.*base="igual"|base="de".*\n.*base="modo".*\n.*base="atual"|base="de".*\n.*base="modo".*\n.*base="anterior"|base="de".*\n.*base="modo".*\n.*base="posterior"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="aparente"|base="de".*\n.*base="modo".*\n.*base="aproximado"|base="de".*\n.*base="modo".*\n.*base="diário"|base="de".*\n.*base="modo".*\n.*base="evidente"|base="de".*\n.*base="modo".*\n.*base="frequente"|base="de".*\n.*base="modo".*\n.*base="freqüente"|base="de".*\n.*base="modo".*\n.*base="grosseiro"|base="de".*\n.*base="modo".*\n.*base="parcial"|base="de".*\n.*base="modo".*\n.*base="possível"|base="de".*\n.*base="modo".*\n.*base="previsível"|base="de".*\n.*base="modo".*\n.*base="provável"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="acertado"|base="de".*\n.*base="modo".*\n.*base="conveniente"|base="de".*\n.*base="modo".*\n.*base="curioso"|base="de".*\n.*base="modo".*\n.*base="espantoso"|base="de".*\n.*base="modo".*\n.*base="esperançoso"|base="de".*\n.*base="modo".*\n.*base="feliz"|base="de".*\n.*base="modo".*\n.*base="impressionante"|base="de".*\n.*base="modo".*\n.*base="inacreditável"|base="de".*\n.*base="modo".*\n.*base="infeliz"|base="de".*\n.*base="modo".*\n.*base="irônico"|base="de".*\n.*base="modo".*\n.*base="lamentável"|base="de".*\n.*base="modo".*\n.*base="sábio"|base="de".*\n.*base="modo".*\n.*base="sensato"|base="de".*\n.*base="modo".*\n.*base="surpreendente"|base="de".*\n.*base="modo".*\n.*base="triste"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="técnica"|base="de".*\n.*base="maneira".*\n.*base="típica"|base="de".*\n.*base="maneira".*\n.*base="franca"|base="de".*\n.*base="maneira".*\n.*base="declarada"|base="de".*\n.*base="maneira".*\n.*base="prévia"|base="de".*\n.*base="maneira".*\n.*base="sincera"|base="de".*\n.*base="maneira".*\n.*base="primeira"|base="de".*\n.*base="maneira".*\n.*base="imediata"|base="de".*\n.*base="maneira".*\n.*base="estrita"|base="de".*\n.*base="maneira".*\n.*base="alta"|base="de".*\n.*base="maneira".*\n.*base="junta"|base="de".*\n.*base="maneira".*\n.*base="honesta"|base="de".*\n.*base="maneira".*\n.*base="relativa"|base="de".*\n.*base="maneira".*\n.*base="figurativa"|base="de".*\n.*base="maneira".*\n.*base="respectiva"|base="de".*\n.*base="maneira".*\n.*base="nova"|base="de".*\n.*base="maneira".*\n.*base="recente"|base="de".*\n.*base="maneira".*\n.*base="especial"|base="de".*\n.*base="maneira".*\n.*base="inicial"|base="de".*\n.*base="maneira".*\n.*base="confidencial"|base="de".*\n.*base="maneira".*\n.*base="essencial"|base="de".*\n.*base="maneira".*\n.*base="normal"|base="de".*\n.*base="maneira".*\n.*base="principal"|base="de".*\n.*base="maneira".*\n.*base="geral"|base="de".*\n.*base="maneira".*\n.*base="igual"|base="de".*\n.*base="maneira".*\n.*base="atual"|base="de".*\n.*base="maneira".*\n.*base="anterior"|base="de".*\n.*base="maneira".*\n.*base="posterior"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="aparente"|base="de".*\n.*base="maneira".*\n.*base="aproximada"|base="de".*\n.*base="maneira".*\n.*base="diária"|base="de".*\n.*base="maneira".*\n.*base="evidente"|base="de".*\n.*base="maneira".*\n.*base="frequente"|base="de".*\n.*base="maneira".*\n.*base="freqüente"|base="de".*\n.*base="maneira".*\n.*base="grosseira"|base="de".*\n.*base="maneira".*\n.*base="parcial"|base="de".*\n.*base="maneira".*\n.*base="possível"|base="de".*\n.*base="maneira".*\n.*base="previsível"|base="de".*\n.*base="maneira".*\n.*base="provável"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt

 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="acertada"|base="de".*\n.*base="maneira".*\n.*base="conveniente"|base="de".*\n.*base="maneira".*\n.*base="curiosa"|base="de".*\n.*base="maneira".*\n.*base="espantosa"|base="de".*\n.*base="maneira".*\n.*base="esperançosa"|base="de".*\n.*base="maneira".*\n.*base="feliz"|base="de".*\n.*base="maneira".*\n.*base="impressionante"|base="de".*\n.*base="maneira".*\n.*base="inacreditável"|base="de".*\n.*base="maneira".*\n.*base="infeliz"|base="de".*\n.*base="maneira".*\n.*base="irônica"|base="de".*\n.*base="maneira".*\n.*base="lamentável"|base="de".*\n.*base="maneira".*\n.*base="sábia"|base="de".*\n.*base="maneira".*\n.*base="sensata"|base="de".*\n.*base="maneira".*\n.*base="surpreendente"|base="de".*\n.*base="maneira".*\n.*base="triste"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000028.txt
 

 
 
 
 
 #compound
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="assim"|form="bem"|form="mal"|form="depressa"|form="devagar"|form="melhor"|form="pior"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000034.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="abaixo"|form="acima"|form="adentro"|form="adiante"|form="afora"|form="aí"|form="além"|form="ali"|form="aqui"|form="aquém"|form="atrás"|form="cá"|form="dentro"|form="embaixo"|form="lá"|form="longe"|form="perto|form="fora"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000038.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="afinal"|form="agora"|form="amanhã"|form="antes"|form="ontem"|form="breve"|form="cedo"|form="constantemente"|form="depois"|form="enfim"|form="hoje"|form="imediatamente"|form="jamais"|form="nunca"|form="sempre"|form="outrora"|form="primeiramente"|form="tarde"|form="provisoriamente"|form="sucessivamente"|form="já"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000040.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="nunca"|form="negativamente"|form="jamais"|form="de".*\n.*form="jeito".*\n.*form="nenhum"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000036.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="não"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000035.txt
 grep -H 'postag="ADV"' $filein | sed "s/^/$filevar /" | grep -E 'form="form="bastante"|form="demais"|form="mais"|form="menos"|form="bem"|form="muito"|form="quanto"|form="quão"|form="quase"|form="tanto"|form="pouco"|form="demasiado"|form="imenso"'  | tr '\t' ' ' | tr -s ' ' >> instances/v000031.txt
 pcregrep -H -M 'base="tecnicamente"|base="tipicamente"|base="francamente"|base="declaradamente"|base="previamente"|base="sinceramente"|base="primeiramente"|base="imediatamente"|base="estritamente"|base="altamente"|base="juntamente"|base="honestamente"|base="relativamente"|base="figurativamente"|base="respectivamente"|base="novamente"|base="recentemente"|base="especialmente"|base="inicialmente"|base="confidencialmente"|base="essencialmente"|base="normalmente"|base="principalmente"|base="geralmente"|base="igualmente"|base="atualmente"|base="anteriormente"|base="posteriormente"|base="segundo"|base="de".*\n.*base="esse".*\n.*base="modo"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000037.txt
 pcregrep -H -M 'base="aparentemente"|base="aproximadamente"|base="diariamente"|base="evidentemente"|base="frequentemente"|base="freqüentemente"|base="maior".*\n.*base="parte".*\n.*base="dos".*\n.*base="casos"|base="parcialmente"|base="possivelmente"|base="previsivelmente"|base="provavelmente"|base="quase".*\n.*base="sempre"|base="quem".*\n.*base="sabe"|base="talvez"|base="tipo".*\n.*base="de"|base="uma".*\n.*base="espécie".*\n.*base="de"|form="acaso"|form="casualmente"|form="porventura"|form="possivelmente"|form="provavelmente"|form="talvez"|form="quiçá"|form="será"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000032.txt
 pcregrep -H -M 'base="absolutamente"|base="amplamente"|base="certamente"|base="claramente"|base="claro"|base="com".*\n.*base="certeza"|base="completamente"|base="consequentemente"|base="conseqüentemente"|base="de".*\n.*base="fato"|base="definitivamente"|base="diretamente"|base="efetivamente"|base="exatamente"|base="exclusivamente"|base="extremamente"|base="facilmente"|base="finalmente"|base="fortemente"|base="independentemente"|base="inevitavelmente"|base="inteiramente"|base="jamais"|base="na".*\n.*base="realidade"|base="naturalmente"|base="necessariamente"|base="nunca"|base="obviamente"|base="particularmente"|base="propriamente"|base="realmente"|base="sem".*\n.*base="dúvida"|base="sempre"|base="significativamente"|base="simplesmente"|base="somente"|base="decerto"|base="certo"|base="sim"|base="não"|base="totalmente"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000029.txt
 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="absoluta"|base="de".*\n.*base="maneira".*\n.*base="ampla"|base="de".*\n.*base="maneira".*\n.*base="certa"|base="de".*\n.*base="maneira".*\n.*base="clara"|base="de".*\n.*base="maneira".*\n.*base="completa"|base="de".*\n.*base="maneira".*\n.*base="consequente"|base="de".*\n.*base="maneira".*\n.*base="conseqüente"|base="de".*\n.*base="maneira".*\n.*base="definitiva"|base="de".*\n.*base="maneira".*\n.*base="direta"|base="de".*\n.*base="maneira".*\n.*base="efetiva"|base="de".*\n.*base="maneira".*\n.*base="exata"|base="de".*\n.*base="maneira".*\n.*base="exclusiva"|base="de".*\n.*base="maneira".*\n.*base="extrema"|base="de".*\n.*base="maneira".*\n.*base="fácil"|base="de".*\n.*base="maneira".*\n.*base="final"|base="de".*\n.*base="maneira".*\n.*base="forte"|base="de".*\n.*base="maneira".*\n.*base="independente"|base="de".*\n.*base="maneira".*\n.*base="inevitável"|base="de".*\n.*base="maneira".*\n.*base="inteira"|base="de".*\n.*base="maneira".*\n.*base="natural"|base="de".*\n.*base="maneira".*\n.*base="necessária"|base="de".*\n.*base="maneira".*\n.*base="óbvia"|base="de".*\n.*base="maneira".*\n.*base="particular"|base="de".*\n.*base="maneira".*\n.*base="própria"|base="de".*\n.*base="maneira".*\n.*base="real"|base="de".*\n.*base="maneira".*\n.*base="significativa"|base="de".*\n.*base="maneira".*\n.*base="simples"|base="de".*\n.*base="maneira".*\n.*base="sa"|base="de".*\n.*base="maneira".*\n.*base="total"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000029.txt
 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="absoluto"|base="de".*\n.*base="modo".*\n.*base="amplo"|base="de".*\n.*base="modo".*\n.*base="certo"|base="de".*\n.*base="modo".*\n.*base="claro"|base="de".*\n.*base="modo".*\n.*base="completo"|base="de".*\n.*base="modo".*\n.*base="consequente"|base="de".*\n.*base="modo".*\n.*base="conseqüente"|base="de".*\n.*base="modo".*\n.*base="definitivo"|base="de".*\n.*base="modo".*\n.*base="direto"|base="de".*\n.*base="modo".*\n.*base="efetivo"|base="de".*\n.*base="modo".*\n.*base="exato"|base="de".*\n.*base="modo".*\n.*base="exclusivo"|base="de".*\n.*base="modo".*\n.*base="extremo"|base="de".*\n.*base="modo".*\n.*base="fácil"|base="de".*\n.*base="modo".*\n.*base="final"|base="de".*\n.*base="modo".*\n.*base="forte"|base="de".*\n.*base="modo".*\n.*base="independente"|base="de".*\n.*base="modo".*\n.*base="inevitável"|base="de".*\n.*base="modo".*\n.*base="inteiro"|base="de".*\n.*base="modo".*\n.*base="natural"|base="de".*\n.*base="modo".*\n.*base="necessário"|base="de".*\n.*base="modo".*\n.*base="óbvio"|base="de".*\n.*base="modo".*\n.*base="particular"|base="de".*\n.*base="modo".*\n.*base="próprio"|base="de".*\n.*base="modo".*\n.*base="real"|base="de".*\n.*base="modo".*\n.*base="significativo"|base="de".*\n.*base="modo".*\n.*base="simples"|base="de".*\n.*base="modo".*\n.*base="so"|base="de".*\n.*base="modo".*\n.*base="total"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000029.txt
 pcregrep -H -M 'base="acertadamente"|base="convenientemente"|base="curiosamente"|base="espantosamente"|base="esperançosamente"|base="felizmente"|base="impressionantemente"|base="inacreditavelmente"|base="infelizmente"|base="ironicamente"|base="lamentavelmente"|base="mesmo"|base="sabiamente"|base="sensatamente"|base="sequer"|base="surpreendentemente"|base="tristemente"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000024.txt
 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="técnico"|base="de".*\n.*base="modo".*\n.*base="típico"|base="de".*\n.*base="modo".*\n.*base="franco"|base="de".*\n.*base="modo".*\n.*base="declarado"|base="de".*\n.*base="modo".*\n.*base="prévio"|base="de".*\n.*base="modo".*\n.*base="sincero"|base="de".*\n.*base="modo".*\n.*base="primeiro"|base="de".*\n.*base="modo".*\n.*base="imediato"|base="de".*\n.*base="modo".*\n.*base="estrito"|base="de".*\n.*base="modo".*\n.*base="alto"|base="de".*\n.*base="modo".*\n.*base="junto"|base="de".*\n.*base="modo".*\n.*base="honesto"|base="de".*\n.*base="modo".*\n.*base="relativo"|base="de".*\n.*base="modo".*\n.*base="figurativo"|base="de".*\n.*base="modo".*\n.*base="respectivo"|base="de".*\n.*base="modo".*\n.*base="novo"|base="de".*\n.*base="modo".*\n.*base="recente"|base="de".*\n.*base="modo".*\n.*base="especial"|base="de".*\n.*base="modo".*\n.*base="inicial"|base="de".*\n.*base="modo".*\n.*base="confidencial"|base="de".*\n.*base="modo".*\n.*base="essencial"|base="de".*\n.*base="modo".*\n.*base="normal"|base="de".*\n.*base="modo".*\n.*base="principal"|base="de".*\n.*base="modo".*\n.*base="geral"|base="de".*\n.*base="modo".*\n.*base="igual"|base="de".*\n.*base="modo".*\n.*base="atual"|base="de".*\n.*base="modo".*\n.*base="anterior"|base="de".*\n.*base="modo".*\n.*base="posterior"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000037.txt
 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="aparente"|base="de".*\n.*base="modo".*\n.*base="aproximado"|base="de".*\n.*base="modo".*\n.*base="diário"|base="de".*\n.*base="modo".*\n.*base="evidente"|base="de".*\n.*base="modo".*\n.*base="frequente"|base="de".*\n.*base="modo".*\n.*base="freqüente"|base="de".*\n.*base="modo".*\n.*base="parcial"|base="de".*\n.*base="modo".*\n.*base="possível"|base="de".*\n.*base="modo".*\n.*base="previsível"|base="de".*\n.*base="modo".*\n.*base="provável"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000032.txt
 pcregrep -H -M 'base="de".*\n.*base="modo".*\n.*base="acertado"|base="de".*\n.*base="modo".*\n.*base="conveniente"|base="de".*\n.*base="modo".*\n.*base="curioso"|base="de".*\n.*base="modo".*\n.*base="espantoso"|base="de".*\n.*base="modo".*\n.*base="esperançoso"|base="de".*\n.*base="modo".*\n.*base="feliz"|base="de".*\n.*base="modo".*\n.*base="impressionante"|base="de".*\n.*base="modo".*\n.*base="inacreditável"|base="de".*\n.*base="modo".*\n.*base="infeliz"|base="de".*\n.*base="modo".*\n.*base="irônico"|base="de".*\n.*base="modo".*\n.*base="lamentável"|base="de".*\n.*base="modo".*\n.*base="sábio"|base="de".*\n.*base="modo".*\n.*base="sensato"|base="de".*\n.*base="modo".*\n.*base="surpreendente"|base="de".*\n.*base="modo".*\n.*base="triste"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000024.txt
 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="técnica"|base="de".*\n.*base="maneira".*\n.*base="típica"|base="de".*\n.*base="maneira".*\n.*base="franca"|base="de".*\n.*base="maneira".*\n.*base="declarada"|base="de".*\n.*base="maneira".*\n.*base="prévia"|base="de".*\n.*base="maneira".*\n.*base="sincera"|base="de".*\n.*base="maneira".*\n.*base="primeira"|base="de".*\n.*base="maneira".*\n.*base="imediata"|base="de".*\n.*base="maneira".*\n.*base="estrita"|base="de".*\n.*base="maneira".*\n.*base="alta"|base="de".*\n.*base="maneira".*\n.*base="junta"|base="de".*\n.*base="maneira".*\n.*base="honesta"|base="de".*\n.*base="maneira".*\n.*base="relativa"|base="de".*\n.*base="maneira".*\n.*base="figurativa"|base="de".*\n.*base="maneira".*\n.*base="respectiva"|base="de".*\n.*base="maneira".*\n.*base="nova"|base="de".*\n.*base="maneira".*\n.*base="recente"|base="de".*\n.*base="maneira".*\n.*base="especial"|base="de".*\n.*base="maneira".*\n.*base="inicial"|base="de".*\n.*base="maneira".*\n.*base="confidencial"|base="de".*\n.*base="maneira".*\n.*base="essencial"|base="de".*\n.*base="maneira".*\n.*base="normal"|base="de".*\n.*base="maneira".*\n.*base="principal"|base="de".*\n.*base="maneira".*\n.*base="geral"|base="de".*\n.*base="maneira".*\n.*base="igual"|base="de".*\n.*base="maneira".*\n.*base="atual"|base="de".*\n.*base="maneira".*\n.*base="anterior"|base="de".*\n.*base="maneira".*\n.*base="posterior"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000037.txt
 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="aparente"|base="de".*\n.*base="maneira".*\n.*base="aproximada"|base="de".*\n.*base="maneira".*\n.*base="diária"|base="de".*\n.*base="maneira".*\n.*base="evidente"|base="de".*\n.*base="maneira".*\n.*base="frequente"|base="de".*\n.*base="maneira".*\n.*base="freqüente"|base="de".*\n.*base="maneira".*\n.*base="grosseira"|base="de".*\n.*base="maneira".*\n.*base="parcial"|base="de".*\n.*base="maneira".*\n.*base="possível"|base="de".*\n.*base="maneira".*\n.*base="previsível"|base="de".*\n.*base="maneira".*\n.*base="provável"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000032.txt
 pcregrep -H -M 'base="de".*\n.*base="maneira".*\n.*base="acertada"|base="de".*\n.*base="maneira".*\n.*base="conveniente"|base="de".*\n.*base="maneira".*\n.*base="curiosa"|base="de".*\n.*base="maneira".*\n.*base="espantosa"|base="de".*\n.*base="maneira".*\n.*base="esperançosa"|base="de".*\n.*base="maneira".*\n.*base="feliz"|base="de".*\n.*base="maneira".*\n.*base="impressionante"|base="de".*\n.*base="maneira".*\n.*base="inacreditável"|base="de".*\n.*base="maneira".*\n.*base="infeliz"|base="de".*\n.*base="maneira".*\n.*base="irônica"|base="de".*\n.*base="maneira".*\n.*base="lamentável"|base="de".*\n.*base="maneira".*\n.*base="sábia"|base="de".*\n.*base="maneira".*\n.*base="sensata"|base="de".*\n.*base="maneira".*\n.*base="surpreendente"|base="de".*\n.*base="maneira".*\n.*base="triste"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000024.txt

 pcregrep -H -M 'base="altamente"|base="cada".*\n.*base="vez".*\n.*base="mais"|base="extremamente"|base="imensamente"|base="incrivelmente"|base="muito"|base="particularmente"|base="terrivelmente"|base="totalmente"|base="tremendamente"|base="certamente"|base="mais"|base="completamente"|base="enormemente"|base="por".*\n.*base="inteiro"|base="perfeitamente"|base="inteiramente"|base="simplesmente"|base="somente"|base="demasiadamente"|base="excessivamente"|base="grandemente"|base="intensamente"|base="nada".*\n.*postag="ADJ"|base="exclusivamente"|postag="V".*\n.*base="com.*\n.*base="tudo"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000023.txt

 pcregrep -H -M 'base="igualmente"|base="nada"|base="nada".*\n.*base="de.*\n.*base="especial"|base="nada.*\n.*base="de.*\n.*base="nada"|base="parcialmente"|base="pouco"|base="suficiente"|base="suficientemente"|base="um".*\n.*base="pouco"|base="vagamente"|base="nem".*\n.*base="mesmo"|base="menos"|base="nada".*\n.*base="de".*\n.*base="mais"|base="essencialmente"|base="levemente"|base="ligeiramente"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000026.txt

 pcregrep -H -M 'base="algo"|base="mais".*\n.*base="ou".*\n.*base="menos"|base="quase"|base="algo".*\n.*base="como"|base="algo".*\n.*base="tipo"|base="talvez"|base="tipo".*\n.*postag="ADJ"|base="meio".*\n.*postag="ADJ"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000030.txt

 pcregrep -H -M 'base="assaz"|base="bastante"|base="bem"|base="demais"|base="mesmo"|base="mui"|base="paca"|base="por".*\n.*base="demais"|base="sobremaneira"|base="sobremodo"|base="tanto".*\n.*base="mais"|base="ultra"|base="um".*\n.*base="tanto"|base="tão"|base="de".*\n.*base="certo"|base="com".*\n.*base="certeza"|base="super"|base="apenas"|base="só".*\n.*postag="V"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000027.txt

 pcregrep -H -M 'extra="aux".*\n.*postag="ADV".*\n.*extra=".* mv"' $filein | sed "s/^/$filevar /" | pcregrep -v 'base="poder".*\n.*\n|base="dever".*\n.*\n|base="conseguir".*\n.*\n|base="parecer".*\n.*\n'  | tr '\t' ' ' | tr -s ' ' >> instances/v000039.txt

 pcregrep -H -M 'extra=".*KOMP"' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000041.txt

# discourse markers, i.e. agora, então, portanto, etc. i.e. conjunctional adverbs

 pcregrep -H -M 'extra=".*kc' $filein | sed "s/^/$filevar /"  | tr '\t' ' ' | tr -s ' ' >> instances/v000042.txt

done < file_index.txt
